coverage:
  status:
    # относительно всего проекта
    project:
      default:
        # https://docs.codecov.io/v1.0/docs/commit-status#section-threshold
        threshold: 10 # разрешить чтобы покрытие упало на 10%

    # относительно сделанных изменений
    patch:
      default:
        threshold: 100 # разрешить чтобы покрытие упало на 100%
