version: 2

defaults: &defaults
#  working_directory: ~/repo
  docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/node:8.9.1 # the primary container, where your job's commands are run (image: circleci/node:4.8.2)

jobs:
  install:
    <<: *defaults
    steps:
      - checkout # check out the code in the project directory
      - restore_cache: # Restores a previously saved cache based on a key (or keys)
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: # used for invoking all command-line programs
          name: Install Dependencies
          command: npm install # yarn install --frozen-lockfile
      - save_cache: # Generates and stores a cache of a file or directory of files
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  build:
    <<: *defaults
    steps:
      - run: npm run build

  tests:
    <<: *defaults
    steps:
      - run: npm run test:unit
      - run: echo "Tests are performed!"

# TODO run lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - tests:
          requires:
            - install
#          filters:
#            branches:
#              only: master
      - build:
          requires:
            - install
            - tests

