version: 2
jobs:
 build:
   docker:
      - image: christiankm01/kilo:1
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: lcc
